### ISSUE TITLE
Symfony 6.3 deprecations

### ISSUE THREAD

**Issue by julien-jourde** [Akollade/mjml-bundle#86]
Hello there,

When running the bundle on Symfony 6.3 environment, I have this deprecation :

`Method "Symfony\Component\DependencyInjection\Extension\ExtensionInterface::load()" might add "void" as a native return type declaration in the future. Do the same in implementation "NotFloran\MjmlBundle\DependencyInjection\MjmlExtension" now to avoid errors or add an explicit @return annotation to suppress this message.`

Have a nice day :)

**Comment by notFloran** [comment]
Thanks for the information.

I have fix that and I just made a new release

**Comment by julien-jourde** [comment]
Thanks you so much.

So fast :fire:
