### ISSUE TITLE
Twig 3.9 deprecation

### ISSUE THREAD

**Issue by shmshd** [Akollade/mjml-bundle#91]
Node implementations that use `echo` or `print` should use `yield` instead and use `#[YieldReady]` attribute. Given this requirement for Twig 3.9, PHP 8 should be the minimum supported version. Is there any reason to support PHP 7?

Currently, there are 3 warnings, 1 from `NodeVisitor/YieldNotReadyNodeVisitor.php` and 2 from the `Compiler.php`.

Deprecation message:
```
User Deprecated: Since twig/twig 3.9: Using "echo" is deprecated, use "yield" instead in "NotFloran\MjmlBundle\Twig\Node", then flag the class with #[YieldReady].
```
Changelog: https://github.com/twigphp/Twig/blob/ad934312cd08b6b466932fdfdd5b97ae680bc28a/CHANGELOG#L25-L29

**Comment by notFloran** [comment]
I fix the deprecation, I will make a new release shortly
